# -*- coding: utf-8 -*-
"""cycle-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pO-9QnGI-m1UdkWaFKJknM9OdDIPuxwh
"""

lst = ["You may read our Python list tutorial before solving the following exercises"]
def longest_word(sentence):
  longest = 0
  sentence = str(sentence)
  sentence = sentence.split()
  for word in sentence:
      if len(word) > longest:
        longest = len(word)
  return f"{word} is the longest with it's {longest} characters"

print(longest_word(lst))

c = "You may read our Python list tutorial before solving the following exercises"
c = c.split()
print(c)

lst = ["You may read our Python list tutorial before solving the following exercises"]

def longest_word(sentence):
  longest = 0
  for text in sentence:
    text = text.split()
    for word in text:
      if len(word) > longest:
        longest = len(word)
  return longest

print(longest_word(lst))



lst = ["You may read our Python list tutorial before solving the following exercises"]

def longest_word(sentence):
  longest = 0
  for text in sentence:
    text = text.split()
    for word in text:
      if len(word) > longest:
        longest = len(word)
  print(f"{word} is the largest word with {len(word)} letters in the given sentence")


print(longest_word(lst))

lst = ["You may read our Python list tutorial before solving the following exercises"]
def longest_word(sentence):
    longest = 0
    longest_word = ""

    for text in sentence:
        words = text.split()
        for word in words:
            if len(word) > longest:
                longest = len(word)
                longest_word = word

    return longest_word, longest

result_word, result_length = longest_word(lst)
print(f"'{result_word}' is the longest word with {result_length} letters in the given sentence")

#from collections import Counter  # returns how many times  all characters in the string  used
my_str = "You may read our Python list tutorial before solving the following exercises"
result = Counter(my_str)
# print(result)
print(result.most_common(2))

#import time
sure = time.time()
# print(sure)
zaman = time.ctime()
# print(zaman)
zaman = time.strftime("%d-%m-%Y")
print(zaman)
zaman = time.strftime("%d-%m-%Y %H:%M:%S")
print(zaman)

#from datetime import date
bugun = date.today()
print(bugun)
belirlenen_tarih = date(2016,8,8)
gecen_sure = bugun - belirlenen_tarih
print(gecen_sure)

#import os
print(os.getcwd())
print(os.listdir())
for dosya in os.listdir():
  print(dosya)

date_string = "Feb 25 2020"
from datetime import datetime,timedelta
result = datetime.strptime(date_string, "%b %d %Y")
print(result)

given_date = datetime(2020, 2, 25)
wanted = timedelta(days=7)
result = given_date + wanted
print(result)

given_date = datetime(2020, 2, 25)
# Day_name  Day_number  Month_name  Year
result = datetime.strftime(given_date, "%A %w %B %Y")
print(result)

given_date = datetime(2020, 7, 26)
# Find the day of the week of a given date
result = given_date.strftime("%A")
print(result)

given_date = datetime(2020, 3, 22, 10, 0, 0)
# Add a week (7 days) and 12 hours to a given date
wanted =timedelta(days=7, hours=12)
result = given_date + wanted
print(result)

# Calculate the date 4 months from the current date
given_date = datetime(2020, 2, 25).date()
print(given_date)
wanted = timedelta(weeks=16)
result = given_date + wanted
print(result) # actually relativedelta must be used but i know this one :))))

# Calculate number of days between two given dates
date_1 = datetime(2020, 2, 25)
date_2 = datetime(2020, 9, 17)
result = date_2 - date_1
print(result)

row = 5
num = 1
for i in range(row,0,-1):
  for j in range(1, i+1):
    print(num,end=" ")
  print(" ")
  num += 1

row = 5
num = 1
for i in range(row,0,-1):
  for j in range(1, i+1):
    print(num,end=" ")
  print(" ")

row = 5
num = 1
for i in range(row,0,-1):
  for j in range(1, i+1):
    print(j,end=" ")
  print(" ")

row = 5
num = 1
for i in range(row,0,-1):
  for j in range(1, i+1):
    print(i,end=" ")
  print(" ")

row = 5
num = 5
for i in range(row,0,-1):
  for j in range(1, i+1):
    print(num,end=" ")
  print(" ")

row = 5
num = 0
for i in range(row,-1,-1):
  for j in range(0, i+1):
    print(num,end=" ")
  print(" ")
  num += 1

row = 5

for i in range(row,-1,-1):
  for j in range(0, i+1):
    print(j,end=" ")
  print(" ")
  j += 1

row = 5
num = 1
for i in range(1,row+1):
  for j in range(1, i+1):
    print(num,end=" ")
  print(" ")
  num += 2

row = 5
num = 1
for i in range(1,row+1):
  for j in range(1, i+1):
    print(num,end=" ")
  print(" ")
  num += 1

rows = 6
for i in range(1, rows):
    for j in range(i, 0, -1):
        print(j, end=' ')
    print("")

rows = 5
for i in range(rows,0,-1):
    for j in range(i, 0, -1):
        print(j, end=' ')
    print("")

start = 1
stop = 2
current_num = stop
for row in range(2, 6):
    for col in range(start, stop):
        current_num -= 1
        print(current_num, end=' ')
    print("")
    start = stop
    stop += row
    current_num = stop

#import time
start = time.time()
rows = 5
for i in range(1, rows+1):
    num = 1
    for j in range(rows+1, 0, -1):
        if j > i:
            print(" ", end=' ')
        else:
            print(num, end=' ')
            num += 1
    print("")
print(" ")
end = time.time()
process_time = end - start
print(process_time)