# -*- coding: utf-8 -*-
"""cycle_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rOCQWNLr7LjIkzc4r56udACCcshF9qY2
"""

print(
    f"Welcome to the guessing game\n"
    f"you have 3 guesses to find the number"
    )
import random


user_count = 3
def guess(x):
    x = random.randint(1,100)
    user = 0
    counter = 0
user_count 
while counter <= 3:
      if not isinstance(user,int):
        print("Please enter a positive number : ")
        user = int(input("Please enter a positive integer : "))
      elif user < x and counter <= user_count:
        counter+= 1
        print(f"Your guess {user} is lower than the number and {user_count - counter} guesses left")
      elif user > x and  counter <= user_count:
        counter +=1
        print(f"Your guess {user} is higher than the number and {user_count - counter} guesses left")
        user = int(input("Please enter a positive integer : "))
      else:
        print("You guessed correctly!")
        break
user = int(input("Please enter a positive integer : "))
guess(user)

'''Write a Python program to find
those numbers which are divisible by 7
and multiples of 5, between 1500 and
2700 (both included).'''
[i for i in range(1500,2701) if i%35==0 and i%5==0 and i%7==0]

'''Write a Python program to convert
temperatures to and from Celsius and
Fahrenheit.
[Formula : c/5 = f-32/9
[where c = temperature in celsius and
f = temperature in fahrenheit ]
Expected Output :
60°C is 140 in Fahrenheit
45°F is 7 in Celsius'''
def converter_temp(number):
   return int((number/5)*9 + 32)
user= int(input())
converter_temp(user)

'''Write a Python program to convert
temperatures to and from Celsius and
Fahrenheit.
[Formula : c/5 = f-32/9
[where c = temperature in celsius and
f = temperature in fahrenheit ]
Expected Output :
60°C is 140 in Fahrenheit
45°F is 7 in Celsius'''
def converter_temp(user):
   if isinstance(user,str):
      user= user.split()
      need = user[1].lower()
      if need == "c":
        required = int(user[0])
        return int((required/5)*9 + 32)
      elif need == "f":
        required = int(user[0])
        return int(((required-32)/9)*5)
user= input("Please enter the value you want to convert in 'number C' format : ")
converter_temp(user)

'''Write a Python program to guess a
number between 1 and 9.
Note : User is prompted to enter a
guess. If the user guesses wrong then
the prompt appears again until the
guess is correct, on successful guess,
user will get a "Well guessed!"
message, and the program will exit.'''
import random
def guess(number):
     x = random.randint(1,10)
     while True:
       user = int(input())
       if user ==  x:
         print("Well guessed!")
         break

user = int(input())
guess(user)

# another solution
import random
target_num, guess_num = random.randint(1, 10), 0
while target_num != guess_num:
    guess_num = int(input('Guess a number between 1 and 10 until you get it right : '))
print('Well guessed!')

'''Write a Python program to construct the following pattern, using a nested for loop.

*
* *
* * *
* * * *
* * * * *
* * * *
* * *
* *
*'''
row = 5
for i in range(1,row+1):
  for j in range(1,i+1):
    print("*",end=' ')
  print(" ")

for i in range(1,row):
  for j in range(row-i,0,-1):
    print("*",end=" ")
  print(" ")

# Write a Python program that accepts a word from the user and reverses it
import time

user = input("Please enter a word :")
start = time.time()
print(user[::-1])
end = time.time()
process_time = end - start
print(process_time)

# another solution
word = input("Input a word to reverse: ")
start = time.time()
for char in range(len(word) - 1, -1, -1):
  print(word[char], end="")
print("\n")
end = time.time()
print(process_time)

import random
x = random.randint(1,10)
print(x)

'''Write a Python program that prints
each item and its corresponding type
from the following list.
Sample List : datalist = [1452, 11.23,
1+2j, True, 'w3resource', (0, -1), [5,
12], {"class":'V', "section":'A'}]'''
datalist = [1452, 11.23, 1+2j, True, 'w3resource', (0, -1), [5, 12], {"class":'V', "section":'A'}]
for i in datalist:
   print(i,type(i))

'''Write a Python program to count the
number of even and odd numbers in a
series of numbers
Sample numbers : numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9)
Expected Output :
Number of even numbers : 5
Number of odd numbers : 4'''
numbers = (1,2,3,4,5, 10, 28,56)
evens =[]
odds = []
for i in numbers:
   if i %2:
     odds.append(i)
   else:
     evens.append(i)
print(
      f"odd numbers in your list : {odds}\n"
      f"even numbers in your list : {evens}"
      )

'''Write a Python program to count the
number of even and odd numbers in a
series of numbers
Sample numbers : numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9)
Expected Output :
Number of even numbers : 5
Number of odd numbers : 4'''
user =input()
user = user.split()
result = list(map(int,user))
evens =[]
odds = []
for i in result:
   if i %2:
     odds.append(i)
   else:
     evens.append(i)
print(
      f"odd numbers in your list : {odds}\n"
      f"even numbers in your list : {evens}"
      )

'''Write a Python program that prints
all the numbers from 0 to 6 except 3
and 6.
Note : Use 'continue' statement.
Expected Output : 0 1 2 4 5'''
for i in range(7):
  if i==3:
    continue
  elif i ==6:
    continue
  print(i)

'''Write a Python program to get the
Fibonacci series between 0 and 50.
Note : The Fibonacci Sequence is the
series of numbers :
0, 1, 1, 2, 3, 5, 8, 13, 21, ....
Every next number is found by adding
up the two numbers before it.
Expected Output : 1 1 2 3 5 8 13 21 34'''


# Initialize the first two Fibonacci numbers
a, b = 0, 1

# Print the first Fibonacci number (0)
print(a, end=' ')

# Calculate and print the next Fibonacci numbers until reaching 50
while b <= 50:
    print(b, end=' ')
    a, b = b, a + b

row = 5
for i in range(row,0,-1):
  for j in range(1,i+1):
    print("*",end=' ')
  print("  ")
for i in range(1,row+1):
  for j in range(1,i + 1):
    print("*",end=' ')
  print("  ")

for i in range(1,10):
  print((str(i)*(2*i-1)).center(17))

for i in range(1,10):
  print(i*str(i))

total = 0
for i in range(75):
    total+=i
print(total)