# -*- coding: utf-8 -*-
"""python_pattern_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sq_DREZ_xLYUPK3bU7ONX7tTkUEsKQdO
"""

row = int(input("Please enter a number : "))
for i in range(1,row+1):
  for j in range(i):
    print(i,end=" ")
  print(" ")

row = int(input("Please enter a number : "))
for i in range(1,row+1):
  for j in range(1,i+1):
    print(j,end=" ")
  print(" ")

row = int(input("Please enter a number : "))
for i in range(row,0,-1):
  for j in range(1,i+1):
    print(i,end=" ")
  print(" ")

row = int(input("Please enter a number : "))
num = 0
for i in range(row,0,-1):
  num += 1
  for j in range(1,i+1):
    print(num,end=" ")
  print(" ")

row = int(input("Please enter a number : "))
for i in range(row,0,-1):
  for j in range(1,i+1):
    print(row,end=" ")
  print(" ")

row = int(input("Please enter a number : "))
num = 1
for i in range(1,row+1):
  for j in range(1,i+1):
    print(num,end=" ")
    num+=2
  print(" ")

row = int(input("Please enter a number : "))
for i in range(1,row+1):
  num = 1
  for j in range(1,i+1):
    print((2*num-1),end=" ")
    num += 1
  print(" ")

row = int(input("Please enter a number : "))
for i in range(1,row+1):
  for j in range(1,i+1):
    print((2*i-1),end=" ")
  print(" ")