#Write a for loop that iterates over the x list and prints out all the elements of the list.
x = [10, 12, 13, 14, 17, 19, 21, 22, 25]

for i in x:
    print(x)

#Write a for loop that iterates over the x list and prints out the remainders of each element of the list divided by 3.

for i in x:
    print(i%3)
x = [10, 12, 13, 14, 17, 19, 21, 22, 25]
#Write a for loop that iterates over the x list and prints out all the elements of the list in reversed order and multiplied by 10.
x = sorted(x,reverse=True)
for i in x:
    print(i*10)

#another solution:
for i in sorted(x,reverse=True):
    print(i*10)    


x = [10, 12, 13, 14, 17, 19, 21, 22, 25]

#Write a for loop that iterates over the x list and prints out all the elements of the list divided by 2 and the string Great job! after the list is exhausted.

for i in x:
    print(i/2)
print("Great Job!")    

#Another solution by using list comprehension:
print([i/2 for i in x ])

#------------------------------------------------

#Write a for loop that iterates over the x list and prints out the index of each element.
x = [10, 12, 13, 14, 17, 19, 21, 22, 25]

for i in x:
  print(f"the index of {i} is {x.index(i)}")

#------another solution
x = [10, 12, 13, 14, 17, 19, 21, 22, 25]

for index, value in enumerate(x):
    print(f"The index of {value} is {index}")
  



#Write a while loop that prints out the value of x squared while x is less than or equal to 5. Be careful not to end up with an infinite loop!
x = 0
x = 0
while x <= 5:
    print(x**2)
    x+=1
#Write a while loop that prints out the value of x times 10 while x is less than or equal to 4 and then prints out Done! when x becomes larger than Be careful not to end up with an infinite loop!
x = 0

while x <= 4:
  print(x*10)
  x+=1
print("Done!")  




#Write a while loop that prints out the value of x plus 10 while x is less than or equal to 15 and the remainder of x divided by 5 is 0. Be careful not to end up with an infinite loop!
x = 10
while x <= 15 and x%5 == 0:
  print(x+10)
  x+=1
print("i am learning")  
# in while loop the first false condition finishes the while loop

#----------------------------------------------


#Write a while loop that prints out the absolute value of x while x is negative. Be careful not to end up with an infinite loop!

x = -7
while x < 0:
  print(-x)
  x += 1
#---------------another solution-------------
x = -7
while x < 0:
  print(abs(x))
  x += 1


#Write a while loop that prints out the value of x times y while x is greater than or equal to 5 and less than 10, and prints out the result of x divided by y when x becomes 10. Be careful not to end up with an infinite loop!

x = 5
y = 2

while x >= 5 and x < 10:
  print(x*y)
  x += 1
print(x / y)  




#Write code that will iterate over the x list and multiply by 10 only the elements that are greater than 20 and print them out to the screen.
#Hint: use nesting!

x = [10, 12, 13, 14, 17, 19, 21, 22, 25]
for i in x:
  if i > 20:
    print(i*10)
#---------------another solution:
x = [10, 12, 13, 14, 17, 19, 21, 22, 25]
print([i*10 for i in x if i > 20])




#Write code that will iterate over the x and y lists and multiply each element of x with each element of y, also printing the results to the screen.
#Hint: use nesting!
x = [2, 4, 6]
y = [5, 10]

x = [2, 4, 6]
y = [5, 10]
for i in x:
  for j in y:
    print(i*j)

#another solution:
print([i*j for i in x for j in y])    


#Write code that will iterate over the x and y lists and multiply each element of x with each element of y that is less than 12, also printing the results to the screen.
#Hint: use nesting!

x = [2, 4, 6, 8]
y = [5, 10, 15, 20]

for i in x:
  for j in y:
    if i and j < 12:
       print(i*j)

#-------------another solution :
print([i*j for i in x for j in y if i and j < 12])



#----------------------------------------

#Write code that will iterate over the x and y lists and multiply each element of x with each element of y that is less than or equal to 10, also printing the results to the screen. For y's elements that are greater than 10, multiply each element of x with y squared.

x = [2, 4, 6, 8]
y = [5, 10, 15, 20]


#----------------------------------------------------

#Write code that will iterate over the range generated by range (9) and for each element that is between 3 and 7 inclusively print out the result of multiplying that element by the second element in the same range.

