# -*- coding: utf-8 -*-
"""workshop_review.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14s9L-Pt-4kQwu4TwKcwgJzRe17QB149l
"""

a = [10,12,13,14,17,19,21,22,25]
for i in a:
  print(i % 3)

for i in sorted(a, reverse=True):
  print(i*10)

for i in a:
    print(i/2)
print('Great job!')

for i in a:
  print(f"{i} elemaninin indexi : {a.index(i)}")

x = 0
while x <= 5 :
  print(x**2)
  x +=1

x = 0
while x <= 4:
  print(x*10)
  x += 1
print('Done!')

x = 10
while x <= 15:
  print(f'{x} sayisinin 10 fazlasi : {x+10} ve 5 ile bolumunden kalan : {x%5}')
  x += 1

x = 10
while x <= 15:
   x+=1
   if x % 5 == 0:
      print(x + 10)

x = -7
while x < 0:
  print(abs(x))
  x += 1

x = 5
y = 2
while x >= 5 and x < 10:
  print(x*y)
  x +=1
  if x == 10:
    print(x / y)

x = 5
y = 2
while x >= 5 and x < 10:
  print(x*y)
  x +=1
print(x / y)

x = [10,12,13,14,17,19,21,22,25]
for num in x:
  if num > 20:
    print(num * 10)

[(i * 10) for i in x if i > 20]

x = [2,4,6]
y = [5,10]
for i in x:
  for j in y:
    print(i * j)

[(i * j) for i in x for j in y]

x = [2,4,6,8]
y = [5,10,15,20]
print([i*j for i in x for j in y if i < 12 if j < 12])

genius = ('Bill', 'Rosuum', 'Guido van', 'Gates')
def merger(*items):
  print(f"For me {genius[0]+' '+genius[3]} and {genius[2]+' '+genius[1]} are geniuses")

merger(*genius)

friends = {'ali' : 35, 'veli' : 45, 'john' : 46, 'mary' : 25, 'emily' : 33}
def meaner(ali, veli, john, mary, emily ):
  average = (ali + veli + john + mary + emily)/5
  print('These people\' age average is : ', average)
meaner(**friends)

friends = {'ali' : 35, 'veli' : 45, 'john' : 46, 'mary' : 25, 'betty' : 33}
def meaner(ali, veli, john, mary, betty ):
  average = (ali + veli + john + mary + betty)/5
  print('These people\' age average is : ', average)
meaner(**friends)

a = '45'
try:
  sayi = int(a)
  print(a,' sayisi integer a cevrildi')
except:
  print(a, 'sayisi integer a cevrilemez')

a = 'abcd'
try:
  sayi = int(a)
  print(a,' sayisi integer a cevrildi')
except:
  print(a, 'sayisi integer a cevrilemez')

try:
  a = int(input('Lutfen bir sayi giriniz : '))
  b = int(input('Lutfen baska bir sayi giriniz : '))
  print(a/b)
except ValueError :
  print('Kardesim lutfen sayi degeri giriniz')
except ZeroDivisionError :
  print('Bir sayi sifira bolunemez')

try:
  a = int(input('Lutfen bir sayi giriniz : '))
  b = int(input('Lutfen baska bir sayi giriniz : '))
  print(a/b)
except ValueError :
  print('Kardesim lutfen sayi degeri giriniz')
except ZeroDivisionError :
  print('Bir sayi sifira bolunemez')
else :
  print('Hicbir hata ile karsilasilmadi')

try:
  a = int(input('Lutfen bir sayi giriniz : '))
  b = int(input('Lutfen baska bir sayi giriniz : '))
  print(a/b)
except ValueError :
  print('Kardesim lutfen sayi degeri giriniz')
except ZeroDivisionError :
  print('Bir sayi sifira bolunemez')
else :
  print('Hicbir hata ile karsilasilmadi')
finally :
  print('Hata olsa da olmasa da calisir')

def factorial(sayi):
  sonuc = 1
  if sayi == 0:
    return 1
  else:
    for i in range(1,sayi+1):
      sonuc *=i
    return sonuc
factorial(5)

import math

math.factorial(5)

math.sqrt(81)

from math import factorial,sqrt

factorial(4) # from math import factorial dedigimiz icin math.factorial yazmamiza gerek kalmadi

import ilk_modulum

help(ilk_modulum)

ilk_modulum.selamlama('serkan')

ilk_modulum.sesli_harfler

ilk_modulum.toplama(3,4)

# import ilk_modulum as im şeklinde iport ettigimizde artik ilk_modulum. şeklinde degil de im. seklinde kullanmalıyız

from math import pi
from math import factorial
from math import log10

print(pi)
print(factorial(4))
print(log10(1000))

import datetime

print(datetime.date.today())
print(datetime.datetime.now())

born_date = int(input('Please enter your bitrh date : '))
current_date = int(datetime.date.today())
def Calc(current_date - born_date):
  return  a = (current_date - born_date)
  print(f'You have lived {a} days ')

import random

cities = ['Istanbul', 'Chicago', 'London', 'Capetown' ]
print(random.choice(cities))

#Given the code below, use the correct method in order to find out the number of elements in my_tup.
my_tup = ("Romania", "Poland", "Estonia", "Bulgaria", "Slovakia", "Slovenia", "Hungary")

number = len(my_tup)
print (number)

#Given the code below, use the correct method in order to find out the index of Slovakia in my_tup.
my_tup = ("Romania", "Poland", "Estonia", "Bulgaria", "Slovakia", "Slovenia", "Hungary")

index = my_tup.index("Slovenia")

print (index)